services:
  postgres:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=scqiunix
      - POSTGRESQL_PASSWORD=xVtkmz5mo8zGmh1xOptZlLTY3dT4Y2A5
      - POSTGRESQL_DATABASE=scqidatabase_ibu5
    ports:
      - "5432:5432"
    volumes:
      - polls_pg_data:/bitnami/postgresql 

volumes:
  polls_pg_data: 