services:
  postgres:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=scqiunix
      - POSTGRESQL_PASSWORD=scqiunix
      - POSTGRESQL_DATABASE=scqidatabase
    ports:
      - "5432:5432"
    volumes:
      - polls_pg_data:/bitnami/postgresql 

volumes:
  polls_pg_data: 